apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs  # Ensure this matches the label of your pods
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      # You can explicitly specify a nodePort if desired:
      nodePort: 30080
